kubernetes-sigs/ingress2gateway

Makefile, cmd/print.go, cmd/print_test.go, go.mod, pkg/i2gw/ingress2gateway.go
/kind feature
This PR introduces 2 new flags which will enable the user to filter Gateway API objects by namespace.
Fixes #30 
```release-note
Add a --namespace / -n flag to support Gateway API object filtering by namespace.
In addition, a --all-namespaces / -A flag to indicate that all namespaces should be used.
The current namespace will be used if none of the flags is specified.
```
=> Add support for resource filtering by namespace

OWNERS
As discussed offline, added myself (@LiorLieberman) to approvers and @levikobi as a reviewer.
N/A
```release-note
NONE
```
/cc @robscott @shaneutt @youngnick 
/assign @robscott
=> Adding LiorLieberman to approvers and levikobi to reviewers

pkg/i2gw/ingress2gateway_test.go, pkg/i2gw/testdata/input-file.json, pkg/i2gw/testdata/input-file.yaml
/kind test
We need this test to get full coverage on all methods that get ingresses from different sources (e.g. from file and from cluster)
Fixes https://github.com/kubernetes-sigs/ingress2gateway/issues/48
```release-note
NONE
```
=> implement test for constructIngressFromCluster

.github/workflows/build.yaml, .github/workflows/release.yaml, go.mod
/kind cleanup
This bumps the go version to 1.20 to match upstream Gateway API.
Fixes #55 
```release-note
NONE
```
/cc @levikobi
=> Bumping go version to 1.20 to match upstream Gateway API

cmd/print.go, pkg/i2gw/ingress2gateway.go, pkg/i2gw/ingress2gateway_test.go
Add a new flag `--provider`, in order to users to choose which concrete providers should be used when executing the 'print' command.
/kind feature
Now, we already refactor the layout in order to support multiple providers #40. We also need a mechanism to enables users to choose which concrete providers should be used when executing the 'print' command.
Fixes #45
```release-note
Add a new flag `--provider`, that enables users to choose which concrete providers should be used when executing the 'print' command.
```
=> Support to specify providers to execute convert action

README.md
This is the follow-up work of  pr #53, Add `--providers` flag to README.md  doc.
Fixes #
```release-note
None
```
=> Add `--providers` flag doc to README.md

.gitignore
The `ingress2gateway` binary created by `make build` is added to the `.gitignore`.
Fixes #
```release-note
NONE
```
=> i2gw binary added to .gitignore

pkg/i2gw/providers/kong/README.md, pkg/i2gw/providers/kong/annotations.go, pkg/i2gw/providers/kong/converter.go, pkg/i2gw/providers/kong/converter_test.go, pkg/i2gw/providers/kong/method_matching_test.go, pkg/i2gw/providers/kong/plugins.go
Kong plugins feature. The `konhq.com/plugins` ingress annotation is converted to a list of `ExtensionRef` filters.
Fixes #
```release-note
[Kong Provider] Add support for converting the `konghq.com/plugins` ingress annotation to a list of `ExtensionRef` HTTPRoute filters.
```
=> Kong plugins feature

CHANGELOG.md
This adds the changelog for v0.1.0. Consensus on this PR means approval for v0.1.0 release
(Also fix some change in release.yaml I accidentally added in the previous PR)
```release-note
NONE
```
/cc @levikobi @robscott
=> Adding changelog for v0.1.0

PROVIDER.md, pkg/i2gw/provider.go, pkg/i2gw/providers/common/converter.go, pkg/i2gw/providers/common/converter_test.go, pkg/i2gw/providers/common/utils.go, pkg/i2gw/providers/ingressnginx/converter.go, pkg/i2gw/providers/ingressnginx/converter_test.go, pkg/i2gw/providers/kong/README.md, pkg/i2gw/providers/kong/converter.go, pkg/i2gw/providers/kong/converter_test.go, pkg/i2gw/providers/kong/header_matching_test.go, pkg/i2gw/providers/kong/implementation_specific.go, pkg/i2gw/providers/kong/method_matching_test.go
/kind feature
Fixes #88
```release-note
Kong supports `ImplementationSpecific` as `PathType` and converts it into `RegularExpression.`
```
=> feat: kong implementationSpecific pathType

go.mod, go.sum, pkg/i2gw/providers/common/converter.go, pkg/i2gw/providers/common/utils.go, pkg/i2gw/providers/common/utils_test.go, pkg/i2gw/providers/ingressnginx/canary.go
/kind bug
Ingress Rules order needs to be preserved when converting into `HTTPRoute` rules.
Fixes #91
```release-note
NONE
```
=> fix: ingress rules order is preserved

cmd/print.go, pkg/i2gw/ingress2gateway.go
/kind feature
Print generated GatewayClasses, TLSRoutes, TCPRoutes and ReferenceGrants.
These resources are already present in the provider conversion logic but are not propagated to the printer yet. The PR fixes this.
Related to the #100. Istio provider would generate TLSRoutes, TCPRoutes and ReferenceGrants for users.
```release-note
Print generated GatewayClasses, TLSRoutes, TCPRoutes and ReferenceGrants in addition to Gateways and HTTPRoutes
```
=> Print generated GatewayClasses, TLSRoutes, TCPRoutes and ReferenceGrants.

pkg/i2gw/ingress2gateway.go, pkg/i2gw/ingress2gateway_test.go, pkg/i2gw/provider.go, pkg/i2gw/providers/ingressnginx/converter.go, pkg/i2gw/providers/ingressnginx/converter_test.go, pkg/i2gw/providers/ingressnginx/ingressnginx.go, pkg/i2gw/providers/ingressnginx/resource_reader.go, pkg/i2gw/providers/ingressnginx/storage.go, pkg/i2gw/providers/istio/istio.go, pkg/i2gw/providers/istio/resource_reader.go, pkg/i2gw/providers/kong/converter.go, pkg/i2gw/providers/kong/converter_test.go, pkg/i2gw/providers/kong/kong.go, pkg/i2gw/providers/kong/resource_reader.go, pkg/i2gw/providers/kong/storage.go
/kind feature
Currently we fetch all the ingresses in the main package and we pass them to all the providers. 
This is not only redundant (as every provider only cares about its own ingresses) but also creates some bugs. (https://github.com/kubernetes-sigs/ingress2gateway/issues/109)
This also increases consistency as we already fetch CRDs at the provider level and store them in a local storage.
Note: This PR is likely to yield some more issues and TODOs that wont be addressed in this PR.
For example changing `ToGatewayAPI` interface function signature that wont need `i2gw.InputResources` anymore.
Another thing would be to revisit `i2gw.InputResources` struct and check if we need it or we will change it to just a list of …
=> Change ingress fetching to be isolated per provider

cmd/print.go, pkg/i2gw/providers/apisix/README.md, pkg/i2gw/providers/apisix/annotations.go, pkg/i2gw/providers/apisix/apisix.go, pkg/i2gw/providers/apisix/converter.go, pkg/i2gw/providers/apisix/http_to_https.go, pkg/i2gw/providers/apisix/http_to_https_test.go, pkg/i2gw/providers/apisix/resource_reader.go, pkg/i2gw/providers/apisix/storage.go
/kind feature
Adds a basic Apache APISIX provider. We will keep improving it but this is a start.
Related to #107 
```release-note
New Apache APISIX provider.
```
=> feat: add initial support for Apache APISIX provider

pkg/i2gw/ingress2gateway.go
/kind bug
Make the tool more robust. Don't read/run k8s client config when reading local file. E.g. user may have incorrect/incompatible .kube_config but the user tries to convert a local file. `.kube_config` file should not affect the tool run in such case.
I've checked all providers, none needs a k8sclient to translate a local file, which is expected.
Fixes #127
```release-note
Skip k8s client creation when reading local file.
```
=> Skip k8s client creation when reading local file.

README.md, cmd/print.go, cmd/root.go
/kind feature
Some users and organizations work with multiple Kubernetes clusters by utilizing multiple config files instead of one. The `--kubeconfig` flag allows you to switch between these clusters by specifying different configuration files.
Fixes #81 
```release-note
Add a `--kubeconfig` flag to specify kubeconfig file location 
```
=> feat: add a kubeconfig flag to specify kubeconfig file location

README.md
Added instructions for installing the binary via Homebrew on macOS and Linux to make it easier for users to obtain the `ingress2gateway` binary. This provides an alternative method to building from the source.
Added instructions for installing the binary via Homebrew on macOS and Linux tomake it easier for users to obtain the  ingress2gateway binary. This provides an alternative method to building from the source.
https://github.com/Homebrew/homebrew-core/pull/166817
Fixes #
```release-note
NONE
```
=> Add instructions for installing binary via Homebrew

pkg/i2gw/ingress2gateway.go, pkg/i2gw/provider.go, pkg/i2gw/providers/common/converter.go, pkg/i2gw/providers/istio/converter.go, pkg/i2gw/providers/istio/converter_test.go, pkg/i2gw/providers/istio/e2e_file_converter_test.go, pkg/i2gw/providers/istio/fixtures/output/5-referencegrants.yaml
/kind feature
`ReferenceGrant` has been promoted to `v1beta1` but we are still using the `alpha` version. We should bump the API.
Fixes #140 
```release-note
Bump `ReferenceGrant` to `v1beta1`
```
=> feat: bump ReferenceGrant to v1beta1

OWNERS
=> move bowei and shaneutt to emeritus_approvers

pkg/i2gw/providers/ingressnginx/canary.go, pkg/i2gw/providers/ingressnginx/canary_test.go
/kind bug
Fixed the issue where canary weight cannot be set to 0.
During testing or debugging, it is common practice to temporarily set the weight of a specific backend to 0 but it is not supported currently in this project
Fixes #136 
```release-note
Add translation when canary-weight is set to 0
```
=> fix: weight can not set to 0

pkg/i2gw/providers/ingressnginx/converter.go, pkg/i2gw/providers/ingressnginx/converter_test.go, pkg/i2gw/providers/ingressnginx/resource_reader.go, pkg/i2gw/providers/ingressnginx/storage.go
/kind bug
Ingress-nginx support mergind different ingresses to one HTTPRoute, but since we used a map to store the ingresses, the order is not consistent, causing tests to be flaky
Fixes #
```release-note
Fixed ingress-nginx conversion tests
```
/cc @levikobi 
FYI @YTGhost
=> fix flakly ingressnginx test

pkg/i2gw/providers/common/converter.go, pkg/i2gw/providers/ingressnginx/canary.go, pkg/i2gw/providers/kong/converter.go, pkg/i2gw/providers/kong/header_matching.go, pkg/i2gw/providers/kong/method_matching.go, pkg/i2gw/providers/kong/plugins.go
/kind bug
Improves error handling across Kong and ingress-nginx providers by removing panic calls and stopping conversions if an error occurs.
Also, prevents the tool from crashing in case no `pathType` is specified.
Fixes #151 
```release-note
* Improves error handling for Kong and Ingress Nginx providers, making them more understandable.
* Prevents the tool from crashing in case no `pathType` is specified
```
=> Improve error handling across kong & ingress-nginx

pkg/i2gw/providers/istio/resource_reader.go, pkg/i2gw/providers/kong/resource_reader.go
/kind bug
Execution should work regardless of whether CRDs are installed or not
Fixes #138 
```release-note
Fix errors when CRDs are not installed in the cluster
```
=> fail soft when crds are not installed

.gitignore, pkg/i2gw/providers/istio/converter.go, pkg/i2gw/providers/istio/converter_test.go
/kind bug
Fixes #154
```release-note
[istio] allow & handle wildcard hosts in VirtualServices
```
=> [istio] fix: handle wildcard hosts in VirtualServices

pkg/i2gw/ingress2gateway.go, pkg/i2gw/provider.go, pkg/i2gw/providers/apisix/apisix.go, pkg/i2gw/providers/apisix/converter.go, pkg/i2gw/providers/apisix/http_to_https.go, pkg/i2gw/providers/apisix/http_to_https_test.go, pkg/i2gw/providers/ingressnginx/canary.go, pkg/i2gw/providers/ingressnginx/converter.go, pkg/i2gw/providers/ingressnginx/converter_test.go, pkg/i2gw/providers/ingressnginx/ingressnginx.go, pkg/i2gw/providers/istio/e2e_file_converter_test.go, pkg/i2gw/providers/istio/istio.go, pkg/i2gw/providers/kong/converter.go, pkg/i2gw/providers/kong/converter_test.go, pkg/i2gw/providers/kong/header_matching.go, pkg/i2gw/providers/kong/header_matching_test.go, pkg/i2gw/providers/kong/kong.go, pkg/i2gw/providers/kong/method_matching.go, pkg/i2gw/providers/kong/method_matching_test.go, pkg/i2gw/providers/kong/plugins.go
/kind feature
Fixes #113 
```release-note
Deprecate `i2gw.InputResources` and remove input resources from `ToGatewayAPI` function
```
=> feat: deprecate i2gw.InputResources

README.md, cmd/print.go, pkg/i2gw/providers/apisix/resource_reader.go, pkg/i2gw/providers/common/converter.go, pkg/i2gw/providers/common/converter_test.go, pkg/i2gw/providers/common/resource_reader.go, pkg/i2gw/providers/common/utils.go, pkg/i2gw/providers/gce/README.md, pkg/i2gw/providers/gce/converter.go, pkg/i2gw/providers/gce/converter_test.go, pkg/i2gw/providers/gce/gce.go, pkg/i2gw/providers/gce/implementation_specific.go, pkg/i2gw/providers/gce/resource_reader.go, pkg/i2gw/providers/gce/storage.go, pkg/i2gw/providers/gce/types.go, pkg/i2gw/providers/gce/utils.go, pkg/i2gw/providers/gce/utils_test.go, pkg/i2gw/providers/ingressnginx/resource_reader.go, pkg/i2gw/providers/kong/resource_reader.go
/kind feature
Adds initial support for GCE provider. Will improve to add more features.
First PR to address issue #87. New features will be added in the following PRs.
```release-note
Added initial support for GCE provider.
```
=> Add support for Google GCE provider

go.sum, pkg/i2gw/providers/gce/converter.go, pkg/i2gw/providers/gce/converter_test.go
/kind bug
Make sure Gateway name is not empty when the GKE ingress class name is not specified.
Fixes #87
```release-note
Fixed an issue that when the ingress class annotation is not specified on a GKE Ingress, the translation would result in a Gateway without name.
```
=> Add ingress class

pkg/i2gw/providers/apisix/http_to_https.go, pkg/i2gw/providers/apisix/notification.go
/kind feature
This PR adds notifications for conversion of Apisix provider
This pull request addresses part of the issue described in #131 
```release-note
Added notifications for Apisix
```
/cc @mlavacca @LiorLieberman
=> added notifications for apisix provider 

pkg/i2gw/providers/ingressnginx/canary.go, pkg/i2gw/providers/ingressnginx/notification.go
/kind feature
This PR adds notifications for conversion of ingress-nginx provider
This pull request addresses part of the issue described in #131 
```release-note
Added notifications for ingress-nginx
```
/cc @mlavacca @LiorLieberman
=> added notifications for ingress-nginx provider

pkg/i2gw/providers/ingressnginx/canary.go, pkg/i2gw/providers/ingressnginx/converter_test.go
/kind bug
Fixes #174 by applying canary only for entitled nginx rule groups, and fix canary evaluation when enabled.
Fixes #174
```release-note
Fix nginx canary annotation conversion
```
=> nginx: apply canary only for enabled rule groups

CHANGELOG.md, README.md
This adds the changelog for v0.3.0 Consensus on this PR means approval for v0.3.0 release
```release-note
None
```
/cc @levikobi @mlavacca
=> release 0.3.0

pkg/i2gw/providers/gce/extensions/input_extensions.go, pkg/i2gw/providers/gce/extensions/output_extensions.go, pkg/i2gw/providers/gce/gce_extensions.go
/kind cleanup
Refactor IR in GCE to allow additional features.
```release-note
None
```
=> Refactor addBackendPolicyIfConfigured to allow future features

pkg/i2gw/intermediate/provider_gce.go, pkg/i2gw/providers/gce/extensions/input_extensions.go, pkg/i2gw/providers/gce/extensions/output_extensions.go, pkg/i2gw/providers/gce/gateway_converter_test.go, pkg/i2gw/providers/gce/gce_extensions.go, pkg/i2gw/providers/gce/ir_converter_test.go
/kind feature
Adding a new feature for GKE Ingress and Gateway conversion.
Adding more feature for #87.
```release-note
Ingress2gateway now supports translating Cloud Armor security policy on GKE Ingress to GCPBackendPolicy on GKE Gateway.
```
=> Add translation for GKE Security Policy

pkg/i2gw/intermediate/provider_gce.go, pkg/i2gw/providers/gce/extensions/input_extensions.go, pkg/i2gw/providers/gce/extensions/output_extensions.go, pkg/i2gw/providers/gce/gateway_converter.go, pkg/i2gw/providers/gce/gateway_converter_test.go, pkg/i2gw/providers/gce/gce.go, pkg/i2gw/providers/gce/ir_converter.go, pkg/i2gw/providers/gce/ir_converter_test.go, pkg/i2gw/providers/gce/resource_reader.go, pkg/i2gw/providers/gce/storage.go, pkg/i2gw/providers/gce/types.go
/kind feature
Adding a new feature for GKE Ingress and Gateway conversion.
Adding more feature for https://github.com/kubernetes-sigs/ingress2gateway/issues/87.
```release-note
Ingress2gateway now supports translating Ssl Policy on GKE Ingress to GCPGatewayPolicy on GKE Gateway.
```
=> Add translation for GKE Ssl Policy

pkg/i2gw/intermediate/provider_gce.go, pkg/i2gw/providers/gce/extensions/input_extensions.go, pkg/i2gw/providers/gce/extensions/output_extensions.go, pkg/i2gw/providers/gce/gateway_converter.go, pkg/i2gw/providers/gce/gateway_converter_test.go, pkg/i2gw/providers/gce/ir_converter.go, pkg/i2gw/providers/gce/ir_converter_test.go, pkg/i2gw/providers/gce/types.go
/kind feature
Adding a new feature for GKE Ingress and Gateway conversion.
Adding more feature for #87.
```release-note
Ingress2gateway now supports translating Custom Health Check on GKE Ingress to HealthCheckPolicy on GKE Gateway.
```
=> Add translation for GKE Custom health check

pkg/i2gw/providers/gce/README.md
Cleanup README.md for GCE on the latest supported features.
Cleanup #87.
```release-note
None
```
=> Update README with latest supported features and references.

pkg/i2gw/providers/openapi3/converter.go, pkg/i2gw/providers/openapi3/notification.go
/kind feature
This PR adds notifications for conversion of OpenAPI3 provider
This pull request addresses part of the issue described in #131 
```release-note
Added notifications for OpenAPI3
```
/cc @mlavacca @LiorLieberman
=> added notifications for openapi3 provider

CHANGELOG.md
This adds the changelog for v0.4.0-rc1 Consensus on this PR means approval for v0.4.0-rc1 release
```release-note
None
```
/cc @robscott @mlavacca
=> add changelog for release 0.4.0-rc1

Makefile, cmd/root.go, cmd/version.go
/kind feature
Adds a `version` command that can be used to display the current binary version.
This is useful for users to be able to tell what version they are running, especially if installing via a package manager like homebrew.
Example:
./ingress2gateway version
ingress2gateway version: v0.4.0
Built with Go version: go1.24.2
* This is implemented via a combination of ldflags (to propogate the git tag info) and debug.BuildInfo (to get the golang version).
* This does not modify the CurrentVersion var in the i2gw package, but plan is to migrate that in a follow-up.
Fixes #213
```release-note
The version of the binary can now be printed …
```
=> Add version command

README.md
Fixes the example `print` command in the README, which currently will print this:
```
./ingress2gateway print
Error: required flag(s) "providers" not set
Usage:
ingress2gateway print [flags]
...
```
* v0.3.0 made the `--providers` print command required, however the README wasn't updated
* Updates the example print command to use --providers=ingress-nginx since at least one provider *must* be specified
* Removes the default option of providers in the table in the README since it no longer exists.
```release-note
NONE
```
=> Fix print command instructions in README

Makefile, cmd/print.go, cmd/version.go, pkg/i2gw/ingress2gateway.go
/kind cleanup
* Previously the git version string was plumbed to cmd.Version via the linker and i2gw had a hardcoded version
* Now the linker propogates the version string to i2gw and the cmd package imports it from there
* Renames `CurrentVersion` to just `Version`
* This has a few effects:
1. You no longer need to manually update i2gw.CurrentVersion whenever there is a release.  Simply tagging the release will work.
2. The generator annotations (gateway.networking.k8s.io/generator) will now use the git version string instead instead of just the hardcoded value.  This means that during local development you will see something like `"ingress2gateway-v0.4.0-5-gabcdef-dirty"` in your generated annotations, letting you know …
=> Refactor CurrentVersion to use the git version string

.golangci.yml
/kind cleanup
Fixes the following two golint warnings:
```
level=warning msg="[config_reader] The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`."
level=warning msg="[lintersdb] The linter \"scopelint\" is deprecated (step 2) and deactivated. It should be removed from the list of disabled linters. https://golangci-lint.run/product/roadmap/#linter-deprecation-cycle"
```
```release-note
NONE
```
=> Fix golint warnings

pkg/i2gw/ingress2gateway.go
Add one of the following kinds:
/kind cleanup
* Previously the help string for `print --providers` had a non-deterministic ordering since it is generated from map keys.
* This will be helpful in tackling #162
*Before (point in time example)*
`
--providers strings                    If present, the tool will try to convert only resources related to the specified providers, supported values are [kong openapi3 apisix cilium gce ingress-nginx istio].
`
*After*
`
--providers strings                    If present, the tool will try to convert only resources related to the specified providers, supported values are [apisix cilium gce ingress-nginx istio kong openapi3].
` …
=> Sort the names of the names of the providers in the print command

cmd/root.go, main.go
/kind bug
The imports the k8s OIDC libraries so that OIDC authentication to the kubernetes apiserver works. At the moment, if you are trying to run `ingress2gateway` against a kubernetes cluster that is configured in your kubeconfig to use OIDC, you get the following error
```
$ ./ingress2gateway print --providers ingress-nginx
Error: failed to create client: no Auth Provider found for name "oidc"
...
```
Once the OIDC auth libraries are imported this now works fine
```
$ ./ingress2gateway print --providers ingress-nginx -n piperj
No resources found in piperj namespace
```
This should also fix GCP and Azure logins as well as those auth libraries are part of this fix as well.
Fixes #215 …
=> Fix OIDC authentication support
