kubernetes-sigs/ingress2gateway

README.md
Documents some of the *current* interpretation of Ingress fields and annotations, which may change over time
Also documents some "ideals" for conflict resolution, that are open for discussion!
=> Document i2gw interpretation of Ingress annotations/fields

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/enhancement.md
Sub of #9
Add Issue template
```release-note
```
=> project: add issue templates

OWNERS
As discussed offline, added myself (@LiorLieberman ) to reviewers.
N/A
```release-note
NONE
```
/cc @robscott 
/assign @robscott
=> Add LiorLieberman to reviewers

pkg/i2gw/aggregator.go, pkg/i2gw/aggregator_test.go, pkg/i2gw/ingress2gateway.go
=> Fix pull-ingress2gateway-verify presubmit

README.md
Helps provide clear instructions that enable developers to quickly and accurately build projects from their source code,
and provides them with opportunities to customize, learn, and participate in open source projects.
```release-note
NONE
```
=> feat: add Build from Source

Makefile, cmd/print.go, cmd/print_test.go, cmd/root.go, hack/boilerplate/boilerplate.generatego.txt, hack/boilerplate/boilerplate.go.txt, hack/boilerplate/boilerplate.py, hack/boilerplate/boilerplate.py.txt, hack/boilerplate/boilerplate.sh.txt, hack/kube-env.sh, hack/verify-all.sh, hack/verify-boilerplate.sh, main.go, pkg/i2gw/aggregator.go, pkg/i2gw/aggregator_test.go, pkg/i2gw/ingress2gateway.go
not sure what kind is, will go without one
adding boilerplate templates and hack/verify-boilerplate.sh
N/A
```release-note
NONE
```
=> add boilerplate templates and verification

README.md
/kind cleanup
Cleans up and formats readme.
```release-note
NONE
```
=> docs: clean up README.md

.github/workflows/release.yaml, .goreleaser.yaml, CHANGELOG.md, RELEASE.md
This PR add docs about the new release process + CHANGELOG.md to track the project changes
Fixes #56 
```release-note
NONE
```
/cc @robscott @shaneutt @levikobi
=> Document the new release process

RELEASE.md
/kind cleanup
fix wording in release.md
/cc @levikobi
=> fix wording

.github/workflows/release.yaml, CHANGELOG.md
This adds the changelog for v0.1.0-rc1. Consensus on this PR means approval for v0.1.0-rc1 release
(Also fix some change in release.yaml I accidentally added in the previous PR)
```release-note
NONE
```
/cc @levikobi @robscott
=> Adding changelog for v0.1.0-rc1

README.md
Add installation headline to the readme
```release-note
NONE
```
=> add installtion headline

.goreleaser.yaml
making github workflow to release draft
-->
so I can confirm the release notes before
```release-note
NONE
```
=> change goreleaser to draft release

OWNERS
Adds @mlavacca as a reviewer for `ingress2gateway`. Thank you Mattia!
```release-note
NONE
```
=> docs: add mattia to reviewers

CHANGELOG.md
This adds the changelog for v0.2.0-rc1. Consensus on this PR means approval for v0.2.0-rc2 release
Fixes #118 
```release-note
None
```
=> Add changelog for release v0.2.0-rc1

.github/workflows/release.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
=> fix go version in release.yaml

CHANGELOG.md, README.md
This adds the changelog for v0.2.0. Consensus on this PR means approval for v0.2.0 release
Fixes #118 
```release-note
None
```
/cc @levikobi @mlavacca
=> Add changelog for release v0.2.0

README.md, cmd/print.go
/kind cleanup
Fixes #
```release-note
The `--input_file` flag has been renamed `--input-file`.
```
=> chore: generic minor fixes

README.md
Adds `apisix` to the list of providers in the README file.
~~Also updates the provider guide to follow the latest changes to how providers are implemented.~~
Fixes #107
```release-note
NONE
```
=> add apisix as a provider to readme and update provider guide

README.md, pkg/i2gw/providers/openapi3/openapi.go
/kind cleanup
The README has been updated with the following changes:
- the list of providers has been moved upward, right after the introduction, and the providers have been sorted alphabetically.
- openapi has been added as a provider
- the list of flags has been updated
- lines length adjustments
Fixes #
```release-note
NONE
```
=> chore: README updated

pkg/i2gw/providers/istio/converter.go, pkg/i2gw/providers/istio/converter_test.go
/kind feature
This PR adds notifications for conversion of Istio Gateway
This pull request addresses part of the issue described in #131 
```release-note
Added notifications for Istio provider
```
/cc @mlavacca @LiorLieberman
=> Added notifications for Istio Gateway conversion

pkg/i2gw/providers/gce/resource_reader.go
/kind feature
Add frontend config to storage when reading from file.
Fix an issue in #194 when reading frontend config from file.
```release-note
None
```
=> Add FrontendConfig to storage when read from file

README.md
`providers` were marked required in #158, but docs still show it as optional
```release-note
```
=> Mark providers as required in documentation

.goreleaser.yaml
/kind feature
This PR fixes the issue in goreleaser.yaml file - update version and replace depracated values in snapshot
Fixes #206 
```release-note
NONE
```
=> fix/update .goreleaser.yaml file

CHANGELOG.md, README.md, pkg/i2gw/ingress2gateway.go
This adds the changelog for v0.4.0 Consensus on this PR means approval for v0.4.0 release
```release-note
None
```
/cc @levikobi @mlavacca @robscott
=> changelog for release-0.4.0

OWNERS
/kind cleanup
```release-note
None
```
/cc @robscott
=> Update ingress2gateway reviewers
